import type { ScoringSettings } from '../types/league.types';

export const DEFAULT_SCORING_SETTINGS: Omit<ScoringSettings, 'id' | 'leagueId'> = {
  ptsWin: 3,
  ptsKoTko: 5,
  ptsSubmission: 5,
  ptsDecision: 2,
  ptsDraw: 1,
  ptsNoContest: 0,
  ptsFinishRd1: 3,
  ptsFinishRd2: 2,
  ptsFinishRd3: 1,
  ptsFinishRd4: 0.5,
  ptsFinishRd5: 0,
  ptsKnockdown: 1,
  ptsSigStrikeLanded: 0.2,
  ptsSigStrikeAttempted: -0.05,
  ptsTotalStrikeLanded: 0.1,
  ptsTakedownLanded: 1.5,
  ptsTakedownAttempted: -0.25,
  ptsSubmissionAttempt: 0.5,
  ptsPerformanceOfNight: 2,
  ptsFightOfNight: 1,
  ptsLoss: 0,
  ptsKoLossPenalty: 0,
  titleFightMultiplier: 1.5,
  scorePrelims: true,
  scoreEarlyPrelims: false,
};
