export const UFC_WEIGHT_CLASSES = [
  {
    slug: 'heavyweight',
    name: 'Heavyweight',
    weightLimitLbs: 265,
    gender: 'male',
    displayOrder: 1,
  },
  {
    slug: 'light-heavyweight',
    name: 'Light Heavyweight',
    weightLimitLbs: 205,
    gender: 'male',
    displayOrder: 2,
  },
  {
    slug: 'middleweight',
    name: 'Middleweight',
    weightLimitLbs: 185,
    gender: 'male',
    displayOrder: 3,
  },
  {
    slug: 'welterweight',
    name: 'Welterweight',
    weightLimitLbs: 170,
    gender: 'male',
    displayOrder: 4,
  },
  {
    slug: 'lightweight',
    name: 'Lightweight',
    weightLimitLbs: 155,
    gender: 'male',
    displayOrder: 5,
  },
  {
    slug: 'featherweight',
    name: 'Featherweight',
    weightLimitLbs: 145,
    gender: 'male',
    displayOrder: 6,
  },
  {
    slug: 'bantamweight',
    name: 'Bantamweight',
    weightLimitLbs: 135,
    gender: 'male',
    displayOrder: 7,
  },
  { slug: 'flyweight', name: 'Flyweight', weightLimitLbs: 125, gender: 'male', displayOrder: 8 },
  {
    slug: 'womens-strawweight',
    name: "Women's Strawweight",
    weightLimitLbs: 115,
    gender: 'female',
    displayOrder: 9,
  },
  {
    slug: 'womens-flyweight',
    name: "Women's Flyweight",
    weightLimitLbs: 125,
    gender: 'female',
    displayOrder: 10,
  },
  {
    slug: 'womens-bantamweight',
    name: "Women's Bantamweight",
    weightLimitLbs: 135,
    gender: 'female',
    displayOrder: 11,
  },
  {
    slug: 'womens-featherweight',
    name: "Women's Featherweight",
    weightLimitLbs: 145,
    gender: 'female',
    displayOrder: 12,
  },
] as const;
