/**
 * Seeds the top ~180 active UFC fighters across all weight classes.
 * Run: npx tsx src/db/seeds/fighters.ts
 */
import { Pool } from 'pg';

const db = new Pool({ connectionString: process.env.DATABASE_URL });

const FIGHTERS: Array<{
  firstName: string;
  lastName: string;
  nickname?: string;
  weightClass: string;
  record: [number, number, number];
  ranking?: number;
  isChampion?: boolean;
  nationality?: string;
  team?: string;
}> = [
  // Heavyweight
  {
    firstName: 'Jon',
    lastName: 'Jones',
    nickname: 'Bones',
    weightClass: 'heavyweight',
    record: [27, 1, 0],
    ranking: 1,
    isChampion: true,
    nationality: 'USA',
    team: 'Jackson-Wink MMA',
  },
  {
    firstName: 'Tom',
    lastName: 'Aspinall',
    nickname: null as any,
    weightClass: 'heavyweight',
    record: [15, 3, 0],
    ranking: 2,
    isChampion: true,
    nationality: 'England',
    team: 'Aspinall Fitness',
  },
  {
    firstName: 'Ciryl',
    lastName: 'Gane',
    nickname: 'Bon Gamin',
    weightClass: 'heavyweight',
    record: [12, 2, 0],
    ranking: 3,
    nationality: 'France',
    team: 'MMA Factory',
  },
  {
    firstName: 'Stipe',
    lastName: 'Miocic',
    nickname: null as any,
    weightClass: 'heavyweight',
    record: [20, 4, 0],
    ranking: 4,
    nationality: 'USA',
  },
  {
    firstName: 'Curtis',
    lastName: 'Blaydes',
    nickname: 'Razor',
    weightClass: 'heavyweight',
    record: [18, 4, 0],
    ranking: 5,
    nationality: 'USA',
    team: 'Roufusport',
  },
  {
    firstName: 'Alexander',
    lastName: 'Volkov',
    nickname: 'Drago',
    weightClass: 'heavyweight',
    record: [37, 10, 0],
    ranking: 6,
    nationality: 'Russia',
  },
  {
    firstName: 'Jailton',
    lastName: 'Almeida',
    nickname: 'Malhadinho',
    weightClass: 'heavyweight',
    record: [20, 2, 0],
    ranking: 7,
    nationality: 'Brazil',
    team: 'Iron Boy MMA',
  },

  // Light Heavyweight
  {
    firstName: 'Alex',
    lastName: 'Pereira',
    nickname: 'Poatan',
    weightClass: 'light-heavyweight',
    record: [12, 2, 0],
    ranking: 1,
    isChampion: true,
    nationality: 'Brazil',
    team: 'Glory MMA',
  },
  {
    firstName: 'Magomed',
    lastName: 'Ankalaev',
    nickname: null as any,
    weightClass: 'light-heavyweight',
    record: [20, 1, 0],
    ranking: 2,
    nationality: 'Russia',
  },
  {
    firstName: 'Jamahal',
    lastName: 'Hill',
    nickname: 'Sweet Dreams',
    weightClass: 'light-heavyweight',
    record: [12, 2, 0],
    ranking: 3,
    nationality: 'USA',
  },
  {
    firstName: 'Jan',
    lastName: 'Blachowicz',
    nickname: 'Polish Power',
    weightClass: 'light-heavyweight',
    record: [30, 10, 0],
    ranking: 4,
    nationality: 'Poland',
  },
  {
    firstName: 'Jiri',
    lastName: 'Prochazka',
    nickname: 'Denisa',
    weightClass: 'light-heavyweight',
    record: [30, 4, 1],
    ranking: 5,
    nationality: 'Czech Republic',
  },
  {
    firstName: 'Khalil',
    lastName: 'Rountree',
    nickname: 'War Horse',
    weightClass: 'light-heavyweight',
    record: [14, 5, 1],
    ranking: 6,
    nationality: 'USA',
    team: 'Pinnacle MMA',
  },

  // Middleweight
  {
    firstName: 'Dricus',
    lastName: 'Du Plessis',
    nickname: 'Stillknocks',
    weightClass: 'middleweight',
    record: [22, 2, 0],
    ranking: 1,
    isChampion: true,
    nationality: 'South Africa',
  },
  {
    firstName: 'Israel',
    lastName: 'Adesanya',
    nickname: 'The Last Stylebender',
    weightClass: 'middleweight',
    record: [24, 4, 0],
    ranking: 2,
    nationality: 'Nigeria',
    team: 'City Kickboxing',
  },
  {
    firstName: 'Robert',
    lastName: 'Whittaker',
    nickname: 'The Reaper',
    weightClass: 'middleweight',
    record: [25, 7, 0],
    ranking: 3,
    nationality: 'Australia',
    team: 'Gracie Jiu Jitsu Penrith',
  },
  {
    firstName: 'Sean',
    lastName: 'Strickland',
    nickname: 'Tarzan',
    weightClass: 'middleweight',
    record: [29, 6, 0],
    ranking: 4,
    nationality: 'USA',
    team: 'Xtreme Couture',
  },
  {
    firstName: 'Paulo',
    lastName: 'Costa',
    nickname: 'Borrachinha',
    weightClass: 'middleweight',
    record: [15, 3, 0],
    ranking: 5,
    nationality: 'Brazil',
    team: 'Evolution MMA',
  },
  {
    firstName: 'Khamzat',
    lastName: 'Chimaev',
    nickname: 'Borz',
    weightClass: 'middleweight',
    record: [14, 0, 0],
    ranking: 6,
    nationality: 'Sweden',
    team: 'Allstars Training Center',
  },
  {
    firstName: 'Nassourdine',
    lastName: 'Imavov',
    nickname: 'The Sniper',
    weightClass: 'middleweight',
    record: [15, 4, 0],
    ranking: 7,
    nationality: 'France',
    team: 'MMA Factory',
  },
  {
    firstName: 'Bo',
    lastName: 'Nickal',
    nickname: null as any,
    weightClass: 'middleweight',
    record: [6, 0, 0],
    ranking: 8,
    nationality: 'USA',
    team: 'Fortis MMA',
  },

  // Welterweight
  {
    firstName: 'Belal',
    lastName: 'Muhammad',
    nickname: 'Remember the Name',
    weightClass: 'welterweight',
    record: [24, 3, 0],
    ranking: 1,
    isChampion: true,
    nationality: 'USA',
    team: 'Roufusport',
  },
  {
    firstName: 'Leon',
    lastName: 'Edwards',
    nickname: 'Rocky',
    weightClass: 'welterweight',
    record: [22, 4, 0],
    ranking: 2,
    nationality: 'England',
    team: 'JDT/Singh MMA',
  },
  {
    firstName: 'Jack',
    lastName: 'Della Maddalena',
    nickname: 'JDM',
    weightClass: 'welterweight',
    record: [16, 2, 0],
    ranking: 3,
    nationality: 'Australia',
    team: 'MMA Underground',
  },
  {
    firstName: 'Colby',
    lastName: 'Covington',
    nickname: 'Chaos',
    weightClass: 'welterweight',
    record: [17, 4, 0],
    ranking: 4,
    nationality: 'USA',
    team: 'American Top Team',
  },
  {
    firstName: 'Gilbert',
    lastName: 'Burns',
    nickname: 'Durinho',
    weightClass: 'welterweight',
    record: [22, 6, 0],
    ranking: 5,
    nationality: 'Brazil',
    team: 'Kill Cliff FC',
  },
  {
    firstName: 'Sean',
    lastName: 'Brady',
    nickname: null as any,
    weightClass: 'welterweight',
    record: [17, 1, 0],
    ranking: 6,
    nationality: 'USA',
    team: 'Fight Hard MMA',
  },
  {
    firstName: 'Shavkat',
    lastName: 'Rakhmonov',
    nickname: 'Nomad',
    weightClass: 'welterweight',
    record: [18, 0, 0],
    ranking: 7,
    nationality: 'Kazakhstan',
    team: 'Tiger Muay Thai',
  },

  // Lightweight
  {
    firstName: 'Islam',
    lastName: 'Makhachev',
    nickname: null as any,
    weightClass: 'lightweight',
    record: [26, 1, 0],
    ranking: 1,
    isChampion: true,
    nationality: 'Russia',
    team: 'AKA',
  },
  {
    firstName: 'Charles',
    lastName: 'Oliveira',
    nickname: 'Do Bronx',
    weightClass: 'lightweight',
    record: [34, 10, 0],
    ranking: 2,
    nationality: 'Brazil',
    team: 'Chute Boxe Diego Lima',
  },
  {
    firstName: 'Dustin',
    lastName: 'Poirier',
    nickname: 'The Diamond',
    weightClass: 'lightweight',
    record: [30, 9, 0],
    ranking: 3,
    nationality: 'USA',
    team: 'Fortis MMA',
  },
  {
    firstName: 'Justin',
    lastName: 'Gaethje',
    nickname: 'The Highlight',
    weightClass: 'lightweight',
    record: [25, 5, 0],
    ranking: 4,
    nationality: 'USA',
    team: 'RMNU/Freedom MMA',
  },
  {
    firstName: 'Beneil',
    lastName: 'Dariush',
    nickname: null as any,
    weightClass: 'lightweight',
    record: [22, 5, 1],
    ranking: 5,
    nationality: 'Iran',
    team: 'Kings MMA',
  },
  {
    firstName: 'Arman',
    lastName: 'Tsarukyan',
    nickname: 'Ahalkalakets',
    weightClass: 'lightweight',
    record: [22, 3, 0],
    ranking: 6,
    nationality: 'Armenia',
    team: 'AKA',
  },
  {
    firstName: 'Michael',
    lastName: 'Chandler',
    nickname: 'Iron',
    weightClass: 'lightweight',
    record: [23, 8, 0],
    ranking: 7,
    nationality: 'USA',
    team: 'Elevation Fight Team',
  },
  {
    firstName: 'Paddy',
    lastName: 'Pimblett',
    nickname: 'The Baddy',
    weightClass: 'lightweight',
    record: [22, 3, 0],
    ranking: 8,
    nationality: 'England',
    team: 'SBG Ireland',
  },
  {
    firstName: 'Conor',
    lastName: 'McGregor',
    nickname: 'The Notorious',
    weightClass: 'lightweight',
    record: [22, 6, 0],
    ranking: 9,
    nationality: 'Ireland',
    team: 'SBG Ireland',
  },

  // Featherweight
  {
    firstName: 'Ilia',
    lastName: 'Topuria',
    nickname: 'El Matador',
    weightClass: 'featherweight',
    record: [16, 0, 0],
    ranking: 1,
    isChampion: true,
    nationality: 'Georgia',
    team: 'NN Fight Team',
  },
  {
    firstName: 'Alexander',
    lastName: 'Volkanovski',
    nickname: 'The Great',
    weightClass: 'featherweight',
    record: [26, 4, 0],
    ranking: 2,
    nationality: 'Australia',
    team: 'City Kickboxing',
  },
  {
    firstName: 'Yair',
    lastName: 'Rodriguez',
    nickname: 'El Pantera',
    weightClass: 'featherweight',
    record: [16, 4, 0],
    ranking: 3,
    nationality: 'Mexico',
    team: 'Lobo Gym',
  },
  {
    firstName: 'Max',
    lastName: 'Holloway',
    nickname: 'Blessed',
    weightClass: 'featherweight',
    record: [26, 7, 0],
    ranking: 4,
    nationality: 'USA',
    team: 'Hawaii Elite MMA',
  },
  {
    firstName: 'Arnold',
    lastName: 'Allen',
    nickname: 'Almighty',
    weightClass: 'featherweight',
    record: [19, 2, 0],
    ranking: 5,
    nationality: 'England',
    team: 'Tristar Gym',
  },
  {
    firstName: 'Diego',
    lastName: 'Lopes',
    nickname: null as any,
    weightClass: 'featherweight',
    record: [25, 7, 0],
    ranking: 6,
    nationality: 'Brazil',
    team: 'X-Gym',
  },
  {
    firstName: 'Brian',
    lastName: 'Ortega',
    nickname: 'T-City',
    weightClass: 'featherweight',
    record: [16, 3, 0],
    ranking: 7,
    nationality: 'USA',
    team: 'Gracie Jiu Jitsu Torrance',
  },

  // Bantamweight
  {
    firstName: 'Merab',
    lastName: 'Dvalishvili',
    nickname: 'The Machine',
    weightClass: 'bantamweight',
    record: [18, 4, 0],
    ranking: 1,
    isChampion: true,
    nationality: 'Georgia',
    team: 'Serra-Longo Fight Team',
  },
  {
    firstName: 'Sean',
    lastName: "O'Malley",
    nickname: 'Sugar',
    weightClass: 'bantamweight',
    record: [18, 2, 0],
    ranking: 2,
    nationality: 'USA',
    team: 'MMA Lab',
  },
  {
    firstName: 'Cory',
    lastName: 'Sandhagen',
    nickname: 'Sandman',
    weightClass: 'bantamweight',
    record: [17, 5, 0],
    ranking: 3,
    nationality: 'USA',
    team: 'Factory X Muay Thai',
  },
  {
    firstName: 'Umar',
    lastName: 'Nurmagomedov',
    nickname: null as any,
    weightClass: 'bantamweight',
    record: [19, 0, 0],
    ranking: 4,
    nationality: 'Russia',
    team: 'AKA',
  },
  {
    firstName: 'Petr',
    lastName: 'Yan',
    nickname: 'No Mercy',
    weightClass: 'bantamweight',
    record: [18, 5, 0],
    ranking: 5,
    nationality: 'Russia',
    team: 'AKA',
  },
  {
    firstName: 'Marlon',
    lastName: 'Vera',
    nickname: 'Chito',
    weightClass: 'bantamweight',
    record: [22, 9, 1],
    ranking: 6,
    nationality: 'Ecuador',
    team: 'ATT',
  },
  {
    firstName: 'Song',
    lastName: 'Yadong',
    nickname: null as any,
    weightClass: 'bantamweight',
    record: [23, 7, 1],
    ranking: 7,
    nationality: 'China',
  },

  // Flyweight
  {
    firstName: 'Alexandre',
    lastName: 'Pantoja',
    nickname: 'The Cannibal',
    weightClass: 'flyweight',
    record: [27, 5, 0],
    ranking: 1,
    isChampion: true,
    nationality: 'Brazil',
    team: 'Palhares/Pantoja',
  },
  {
    firstName: 'Brandon',
    lastName: 'Moreno',
    nickname: 'The Assassin Baby',
    weightClass: 'flyweight',
    record: [22, 7, 2],
    ranking: 2,
    nationality: 'Mexico',
    team: 'Entram Gym',
  },
  {
    firstName: 'Amir',
    lastName: 'Albazi',
    nickname: 'The Prince',
    weightClass: 'flyweight',
    record: [16, 1, 0],
    ranking: 3,
    nationality: 'Iraq',
    team: 'PMA',
  },
  {
    firstName: 'Matheus',
    lastName: 'Nicolau',
    nickname: 'Pretty Boy',
    weightClass: 'flyweight',
    record: [20, 3, 1],
    ranking: 4,
    nationality: 'Brazil',
    team: 'Vitor Belfort Team',
  },
  {
    firstName: 'Tatsuro',
    lastName: 'Taira',
    nickname: null as any,
    weightClass: 'flyweight',
    record: [16, 0, 0],
    ranking: 5,
    nationality: 'Japan',
    team: 'BRAVE GYM',
  },

  // Women's Strawweight
  {
    firstName: 'Zhang',
    lastName: 'Weili',
    nickname: 'Magnum',
    weightClass: 'womens-strawweight',
    record: [25, 3, 0],
    ranking: 1,
    isChampion: true,
    nationality: 'China',
    team: 'ATT',
  },
  {
    firstName: 'Rose',
    lastName: 'Namajunas',
    nickname: 'Thug',
    weightClass: 'womens-strawweight',
    record: [12, 7, 0],
    ranking: 2,
    nationality: 'USA',
    team: 'Factory X Muay Thai',
  },
  {
    firstName: 'Yan',
    lastName: 'Xiaonan',
    nickname: 'Fury',
    weightClass: 'womens-strawweight',
    record: [18, 4, 0],
    ranking: 3,
    nationality: 'China',
  },
  {
    firstName: 'Tatiana',
    lastName: 'Suarez',
    nickname: 'Tate',
    weightClass: 'womens-strawweight',
    record: [10, 0, 0],
    ranking: 4,
    nationality: 'USA',
    team: 'Team Alpha Male',
  },
  {
    firstName: 'Virna',
    lastName: 'Jandiroba',
    nickname: 'Carcará',
    weightClass: 'womens-strawweight',
    record: [21, 5, 0],
    ranking: 5,
    nationality: 'Brazil',
  },
  {
    firstName: 'Jessica',
    lastName: 'Andrade',
    nickname: 'Bate Estaca',
    weightClass: 'womens-strawweight',
    record: [25, 12, 0],
    ranking: 6,
    nationality: 'Brazil',
    team: 'Evolucao Thai',
  },

  // Women's Flyweight
  {
    firstName: 'Valentina',
    lastName: 'Shevchenko',
    nickname: 'Bullet',
    weightClass: 'womens-flyweight',
    record: [24, 4, 0],
    ranking: 1,
    isChampion: false,
    nationality: 'Kyrgyzstan',
    team: 'Tiger Muay Thai',
  },
  {
    firstName: 'Erin',
    lastName: 'Blanchfield',
    nickname: 'Cold Blooded',
    weightClass: 'womens-flyweight',
    record: [12, 2, 0],
    ranking: 2,
    nationality: 'USA',
    team: 'Fight Hard MMA',
  },
  {
    firstName: 'Manon',
    lastName: 'Fiorot',
    nickname: 'The Beast',
    weightClass: 'womens-flyweight',
    record: [12, 1, 0],
    ranking: 3,
    nationality: 'France',
    team: 'MMA Factory',
  },
  {
    firstName: 'Taila',
    lastName: 'Santos',
    nickname: 'Snake',
    weightClass: 'womens-flyweight',
    record: [22, 4, 0],
    ranking: 4,
    nationality: 'Brazil',
    team: 'ATT',
  },
  {
    firstName: 'Amanda',
    lastName: 'Ribas',
    nickname: 'Twister',
    weightClass: 'womens-flyweight',
    record: [14, 4, 0],
    ranking: 5,
    nationality: 'Brazil',
    team: 'Ribas MMA',
  },

  // Women's Bantamweight
  {
    firstName: 'Julianna',
    lastName: 'Pena',
    nickname: 'The Venezuelan Vixen',
    weightClass: 'womens-bantamweight',
    record: [13, 5, 0],
    ranking: 1,
    isChampion: true,
    nationality: 'USA',
    team: 'Fight Ready',
  },
  {
    firstName: 'Raquel',
    lastName: 'Pennington',
    nickname: 'Rocky',
    weightClass: 'womens-bantamweight',
    record: [16, 7, 0],
    ranking: 2,
    nationality: 'USA',
    team: 'Factory X Muay Thai',
  },
  {
    firstName: 'Irene',
    lastName: 'Aldana',
    nickname: 'Ebony',
    weightClass: 'womens-bantamweight',
    record: [15, 8, 0],
    ranking: 3,
    nationality: 'Mexico',
    team: 'Entram Gym',
  },
  {
    firstName: 'Macy',
    lastName: 'Chiasson',
    nickname: 'The Shocker',
    weightClass: 'womens-bantamweight',
    record: [9, 3, 0],
    ranking: 4,
    nationality: 'USA',
    team: 'Fortis MMA',
  },
];

async function seed() {
  console.log(`Seeding ${FIGHTERS.length} fighters...`);

  for (const fighter of FIGHTERS) {
    const {
      rows: [wc],
    } = await db.query(`SELECT id FROM weight_classes WHERE slug = $1`, [fighter.weightClass]);
    if (!wc) {
      console.warn(
        `Weight class not found: ${fighter.weightClass} (${fighter.firstName} ${fighter.lastName})`,
      );
      continue;
    }

    await db.query(
      `
      INSERT INTO fighters (
        first_name, last_name, nickname, weight_class_id,
        record_wins, record_losses, record_draws,
        ranking, is_champion, nationality, team, status
      ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'active')
      ON CONFLICT DO NOTHING
    `,
      [
        fighter.firstName,
        fighter.lastName,
        fighter.nickname ?? null,
        wc.id,
        fighter.record[0],
        fighter.record[1],
        fighter.record[2],
        fighter.ranking ?? null,
        fighter.isChampion ?? false,
        fighter.nationality ?? null,
        fighter.team ?? null,
      ],
    );
  }

  console.log('Fighter seed complete.');
  await db.end();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
